### PR TITLE
Fix parallel experiment issues

### PR DESCRIPTION
**Pull request by khansaad**
Signed-off-by: Saad Khan <saakhan@redhat.com>

This PR aims to fix the existing parallel experiments issues #103 and #104 .

- Added constructor for TrialDetails class to initialize it for every new experiment.

- Moved the threadCondition inside the constructor in the HPOExperiment class to create a separate lock for each experiment threads.

### CODE REVIEW

**Comment by khansaad** [comment]
Successfully tested on Native and Minikube with 100 experiments (Results attached)

Openshift Testing in progress

[Minikube_hpo_scale_test_results.zip](https://github.com/kruize/hpo/files/9658374/Minikube_hpo_scale_test_results.zip)

[Native_hpo_scale_test_results.zip](https://github.com/kruize/hpo/files/9658333/Native_hpo_scale_test_results.zip)

**Comment by khansaad** [comment]
[Openshift_quicklabb_hpo_scale_test_results.zip](https://github.com/kruize/hpo/files/9673042/Openshift_quicklabb_hpo_scale_test_results.zip)

Attached openshift test results done on quicklab cluster

**Review by dinogun — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
@khansaad looks like the commit is not GPG signed

**Comment by khansaad** [comment]
> @khansaad looks like the commit is not GPG signed

Sorry, missed adding it.
Updated now.

**Pull request merged**
