### PR TITLE
Gracefully handle exception/errors

### PR DESCRIPTION
**Pull request by khansaad**
This PR contains changes to improve error handling in HPO. 
Added new file to include error constants and HPO messages.
Updated Json_validator to thoroughly validate the search_space json values as well.

This will resolve issues #32 , #33 and #34

### CODE REVIEW

**Comment by chandrams** [comment]
@khansaad - There are still exceptions thrown when experiment_name or operation field itself is not specified in the json, whereas not specifying experiment_id throws 400. We will need to keep the error messages consistent. Can you please take a look at these.

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56434)
Traceback (most recent call last):
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 72, in do_POST
    self.handle_generate_new_operation(json_object)
  File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 120, in handle_generate_new_operation
    existingExperiment = hpo_service.instance.containsExperiment(json_object["search_space"]["experiment_name"])
KeyError: 'experiment_name'
----------------------------------------

(base) [csubrama@csubrama no-operation]$ cat service.log 
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 56444)
Traceback (most recent call last):
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 71, in do_POST
    if json_object["operation"] == "EXP_TRIAL_GENERATE_NEW":
KeyError: 'operation'
----------------------------------------

(base) [csubrama@csubrama no-id]$ cat service.log 
2022-06-23 16:11:45 - ERROR - rest_service - 'experiment_id' is a required property
127.0.0.1 - - [23/Jun/2022 16:11:45] "POST /experiment_trials HTTP/1.1" 400 -
```

**Comment by khansaad** [comment]
> @khansaad - There are still exceptions thrown when experiment_name or operation field itself is not specified in the json, whereas not specifying experiment_id throws 400. We will need to keep the error messages consistent. Can you please take a look at these.
> 
> ```
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 56434)
> Traceback (most recent call last):
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 720, in __init__
>     self.handle()
>   File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 415, in handle_one_request
>     method()
>   File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 72, in do_POST
>     self.handle_generate_new_operation(json_object)
>   File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 120, in handle_generate_new_operation
>     existingExperiment = hpo_service.instance.containsExperiment(json_object["search_space"]["experiment_name"])
> KeyError: 'experiment_name'
> ----------------------------------------
> 
> (base) [csubrama@csubrama no-operation]$ cat service.log 
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 56444)
> Traceback (most recent call last):
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 720, in __init__
>     self.handle()
>   File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 415, in handle_one_request
>     method()
>   File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 71, in do_POST
>     if json_object["operation"] == "EXP_TRIAL_GENERATE_NEW":
> KeyError: 'operation'
> ----------------------------------------
> 
> (base) [csubrama@csubrama no-id]$ cat service.log 
> 2022-06-23 16:11:45 - ERROR - rest_service - 'experiment_id' is a required property
> 127.0.0.1 - - [23/Jun/2022 16:11:45] "POST /experiment_trials HTTP/1.1" 400 -
> ```

Updated the code now to handle this and other negative cases

**Comment by chandrams** [comment]
@khansaad - Can you run the testsuite and check, I still see these 3 failures:

 operation_generate_subsequent
  invalid-result-value
  post_same_id_different_exp_result

Invalid result value (passing xyz) with this exception :
```
Exception happened during processing of request from ('127.0.0.1', 43740)
Traceback (most recent call last):
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 415, in handle_one_request
    method()
  File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 62, in do_POST
    json_object = json.loads(str_object)
  File "/home/csubrama/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/home/csubrama/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/csubrama/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 154 (char 153)
```

**Comment by khansaad** [comment]
> @khansaad - Can you run the testsuite and check, I still see these 3 failures:
> 
> operation_generate_subsequent invalid-result-value post_same_id_different_exp_result
> 
> Invalid result value (passing xyz) with this exception :
> 
> ```
> Exception happened during processing of request from ('127.0.0.1', 43740)
> Traceback (most recent call last):
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 316, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 347, in process_request
>     self.finish_request(request, client_address)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/home/csubrama/anaconda3/lib/python3.8/socketserver.py", line 720, in __init__
>     self.handle()
>   File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 427, in handle
>     self.handle_one_request()
>   File "/home/csubrama/anaconda3/lib/python3.8/http/server.py", line 415, in handle_one_request
>     method()
>   File "/home/csubrama/github/saad/hpo/src/rest_service.py", line 62, in do_POST
>     json_object = json.loads(str_object)
>   File "/home/csubrama/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/home/csubrama/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/csubrama/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 154 (char 153)
> ```

This is fixed now.

**Comment by dinogun** [comment]
@johnaohara FYI the result codes will change with this PR, might affect HPOaaS

**Pull request merged**
