### PR TITLE
Included tests to validate support for multiple experiments

### PR DESCRIPTION
**Pull request by chandrams**
Included tests to validate support for multiple experiments

### CODE REVIEW

**Comment by dinogun** [comment]
@chandrams I am worried that by splitting the tests on the basis of gRPC and REST API, we might end up not having parity across both the test suites. Can we make sure we have something like this

```
test_feature_a() {
     test_feature_a_using_REST_API()
     test_feature_a_using_gRPC()
}
```

We can also maintain the two functions in the same file. This way a developer working on adding a test will not have to keep switching files and all related test content for testing a specific feature will be in the same place.

Also I would suggest that we split the files based on features / group of related features. That way we can keep the files short and have only related content in them.

**Comment by dinogun** [comment]
@chandrams can you please resolve conflicts

**Review by dinogun — COMMENTED** [review]
@chandrams the code looks much better organized now, thanks!
One comment, didnt see some grpc equivalents for API tests (eg operation_generate_subsequent), is this something that will be added?

**Comment by chandrams** [comment]
@dino Yes, grpc has only sanity & multiple experiments. Will be adding the other tests for grpc.

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
