### PR TITLE
Enabled HPO tests to run on minikube / openshift cluster

### PR DESCRIPTION
**Pull request by chandrams**
Enabled HPO tests to run on minikube cluster

### CODE REVIEW

**Comment by dinogun** [comment]
@chandrams please resolve conflicts

**Comment by chandrams** [comment]
I have resolved the conflicts & updated openshift changes, testing these.

**Comment by chandrams** [comment]
I have tested it on minikube, opened an issue #77 for grpc test failures. Openshift sanity test has passed. There are failures with other tests, which I'm investigating.  Meanwhile, this PR can be reviewed.

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
